import React, {useEffect, useRef, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Stage, Layer, Rect, Text, Image as KImage, Transformer} from 'react-konva';
import './visual-editor.css';

type Element={id:string,type:'text'|'rect'|'image',x:number,y:number,width:number,height:number,rotation:number,text?:string,src?:string,fill?:string,fontSize?:number};
type Slide={id:number,position:number,title:string,elements:Element[],save_url:string};
const uid=()=>crypto.randomUUID();
function useImageSource(src:string){const [image,setImage]=useState<HTMLImageElement>();useEffect(()=>{const next=new Image;next.onload=()=>setImage(next);next.src=src},[src]);return image}
function Picture({item,onSelect,onChange,nodeRef}:any){const image=useImageSource(item.src);return <KImage ref={nodeRef} image={image} {...item} draggable onClick={onSelect} onTap={onSelect} onDragEnd={e=>onChange({...item,x:e.target.x(),y:e.target.y()})} onTransformEnd={e=>{const n=e.target,sx=n.scaleX(),sy=n.scaleY();n.scaleX(1);n.scaleY(1);onChange({...item,x:n.x(),y:n.y(),rotation:n.rotation(),width:Math.max(20,n.width()*sx),height:Math.max(20,n.height()*sy)})}}/>}
function App(){const root=document.querySelector('#visual-editor') as HTMLElement,data=JSON.parse(root.dataset.presentation||'{}'),[slides,setSlides]=useState<Slide[]>(data.slides),[active,setActive]=useState(0),[selected,setSelected]=useState<string|null>(null),[status,setStatus]=useState('Guardado'),[history,setHistory]=useState<Element[][]>([]),tr=useRef<any>(null),nodes=useRef<Record<string,any>>({});const slide=slides[active];
 const update=(elements:Element[],remember=true)=>{if(remember)setHistory(h=>[...h.slice(-30),slide.elements]);setSlides(s=>s.map((v,i)=>i===active?{...v,elements}:v));setStatus('Guardando…')};
 useEffect(()=>{const timer=setTimeout(async()=>{if(status!=='Guardando…')return;const r=await fetch(slide.save_url,{method:'PUT',headers:{'Content-Type':'application/json','Accept':'application/json','X-CSRF-TOKEN':(document.querySelector('meta[name=csrf-token]') as HTMLMetaElement).content},body:JSON.stringify({elements:slide.elements})});setStatus(r.ok?'Guardado':'Error al guardar')},450);return()=>clearTimeout(timer)},[slide.elements]);
 useEffect(()=>{if(tr.current){tr.current.nodes(selected&&nodes.current[selected]?[nodes.current[selected]]:[]);tr.current.getLayer()?.batchDraw()}},[selected,slide.elements]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.key==='Delete'||e.key==='Backspace')&&selected){e.preventDefault();update(slide.elements.filter(x=>x.id!==selected));setSelected(null)}if((e.ctrlKey||e.metaKey)&&e.key==='z'){e.preventDefault();const prev=history.at(-1);if(prev){setHistory(h=>h.slice(0,-1));update(prev,false)}}};addEventListener('keydown',key);return()=>removeEventListener('keydown',key)},[selected,slide,history]);
 const change=(next:Element)=>update(slide.elements.map(x=>x.id===next.id?next:x));const addText=()=>update([...slide.elements,{id:uid(),type:'text',x:150,y:120,width:420,height:100,rotation:0,text:'Escribe aquí',fill:'#102a2e',fontSize:48}]);const addRect=()=>update([...slide.elements,{id:uid(),type:'rect',x:220,y:220,width:260,height:150,rotation:0,fill:'#ff6846'}]);const addImage=(file:File)=>{const reader=new FileReader;reader.onload=()=>update([...slide.elements,{id:uid(),type:'image',x:180,y:120,width:420,height:280,rotation:0,src:String(reader.result)}]);reader.readAsDataURL(file)};
 return <div className="ve"><header><a href={data.edit_url}>← Salir</a><b>{data.title}</b><span>{status}</span><button onClick={()=>{const prev=history.at(-1);if(prev){setHistory(h=>h.slice(0,-1));update(prev,false)}}}>↶ Deshacer</button><button>Presentar</button></header><aside><h3>Agregar</h3><button onClick={addText}>A Texto</button><button onClick={addRect}>□ Forma</button><label>▧ Imagen<input type="file" accept="image/*" onChange={e=>e.target.files?.[0]&&addImage(e.target.files[0])}/></label><h3>Interacciones</h3><p>Encuesta</p><p>Nube de palabras</p><p>Pregunta abierta</p><p>Reacciones</p></aside><nav><h3>Páginas</h3>{slides.map((s,i)=><button className={i===active?'active':''} onClick={()=>{setActive(i);setSelected(null)}}><b>{i+1}</b>{s.title||'Sin título'}</button>)}</nav><main><div className="ruler">Lienzo 1280 × 720</div><Stage width={960} height={540} scaleX={.75} scaleY={.75} onMouseDown={e=>{if(e.target===e.target.getStage())setSelected(null)}}><Layer><Rect width={1280} height={720} fill="#fffdf8"/>{slide.elements.map(item=>item.type==='text'?<Text key={item.id} ref={n=>{nodes.current[item.id]=n}} {...item} draggable onClick={()=>setSelected(item.id)} onDblClick={()=>{const text=prompt('Editar texto',item.text);if(text!==null)change({...item,text})}} onDragEnd={e=>change({...item,x:e.target.x(),y:e.target.y()})} onTransformEnd={e=>{const n=e.target,s=n.scaleX();n.scaleX(1);n.scaleY(1);change({...item,x:n.x(),y:n.y(),rotation:n.rotation(),width:Math.max(40,n.width()*s),fontSize:Math.max(10,(item.fontSize||40)*s)})}}/>:item.type==='rect'?<Rect key={item.id} ref={n=>{nodes.current[item.id]=n}} {...item} draggable onClick={()=>setSelected(item.id)} onDragEnd={e=>change({...item,x:e.target.x(),y:e.target.y()})} onTransformEnd={e=>{const n=e.target;change({...item,x:n.x(),y:n.y(),rotation:n.rotation(),width:n.width()*n.scaleX(),height:n.height()*n.scaleY()});n.scaleX(1);n.scaleY(1)}}/>:<Picture key={item.id} ref={(n:any)=>nodes.current[item.id]=n} item={item} selected={selected===item.id} onSelect={()=>setSelected(item.id)} onChange={change}/>)}<Transformer ref={tr}/></Layer></Stage><small>Doble clic para editar texto · Supr para eliminar · arrastra y redimensiona libremente</small></main></div>}
createRoot(document.querySelector('#visual-editor')!).render(<App/>);
